import { type ClientSchema, a, defineData } from "@aws-amplify/backend";

/*
 * Schema för Smart Greenhouse Monitoring System
 * Modeller: SensorReading, Alert, SMHISnapshot
 */
const schema = a.schema({
  // ── Sensor readings pushed by AWS IoT Core via Lambda ──────────────────
  SensorReading: a
    .model({
      deviceId:     a.string().required(),   // e.g. "greenhouse-01"
      timestamp:    a.string().required(),   // ISO 8601
      temperature:  a.float().required(),    // °C  (DHT22)
      humidity:     a.float().required(),    // %RH (DHT22)
      soilMoisture: a.float().required(),    // %   (capacitive sensor)
      lightLevel:   a.float().required(),    // lux (BH1750)
      vpd:          a.float(),              // Vapour Pressure Deficit kPa
    })
    .authorization((allow) => [
      allow.authenticated().to(["read"]),
      allow.publicApiKey().to(["create", "read"]),
    ]),

  // ── Threshold alerts generated by Lambda ───────────────────────────────
  Alert: a
    .model({
      deviceId:   a.string().required(),
      timestamp:  a.string().required(),
      alertType:  a.string().required(),  // "HIGH_TEMP" | "LOW_SOIL" | "LOW_LIGHT"
      value:      a.float().required(),
      threshold:  a.float().required(),
      resolved:   a.boolean().required(),
    })
    .authorization((allow) => [
      allow.authenticated().to(["read", "update"]),
      allow.publicApiKey().to(["create", "read", "update"]),
    ]),

  // ── SMHI outdoor weather snapshots (fetched every 30 min by Lambda) ────
  SMHISnapshot: a
    .model({
      timestamp:       a.string().required(),
      location:        a.string().required(),  // "Stockholm"
      outdoorTemp:     a.float().required(),
      outdoorHumidity: a.float(),
      precipitation:   a.float(),
      windSpeed:       a.float(),
    })
    .authorization((allow) => [
      allow.authenticated().to(["read"]),
      allow.publicApiKey().to(["create", "read"]),
    ]),
});

export type Schema = ClientSchema<typeof schema>;

export const data = defineData({
  schema,
  authorizationModes: {
    defaultAuthorizationMode: "userPool",
    apiKeyAuthorizationMode: {
      expiresInDays: 365,
    },
  },
});
